[green_agent]
agentbeats_id = "019b505d-5492-7970-a17c-37d317ebc2af"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_BASE_URL = "${OPENAI_BASE_URL}" }

[[participants]]
agentbeats_id = "019b50a6-7acd-79e2-bc5e-f93b0a4235e7"
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_BASE_URL = "${OPENAI_BASE_URL}" }

[config]
# Add your assessment config here
domain = "airline"
num_tasks = 3
